name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-2.0
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libglew-dev
    - name: Build
      run: |
        cmake .
        make Runtime
